const copy={
  en:{library:'DIGITAL LIBRARY',choose:'CHOOSE A STORY',eyebrow:'READ · LEARN · REMEMBER',title:'THE LIBRARY',intro:'Choose a world, then read it as a graphic novel or as text with interactive vocabulary.',fantasy:'EPIC FANTASY',series:'THE STONES OF SPARTA',bookTitle:'THE FIRST AWAKENING',hellboy:'Misha chooses Sparta and begins his search for the Infinity Stones.',folk:'FOLK TALES',folkTitle:'UKRAINIAN FOLK TALES',folkBadge:'UKRAINIAN FOLK TALE',turnip:'THE TURNIP',turnipCopy:'A warm tale about the smallest helper accomplishing what nobody else can.',mitten:'THE MITTEN',mittenCopy:'A lost woolen mitten becomes a winter home for seven forest friends.',graphic:'GRAPHIC NOVEL',novel:'NOVEL',polishCategory:'FOLK TALES',polishTitle:'POLISH FOLK TALES',polishBadge:'POLISH FOLK TALES · VOLUME I',polishBook:'8 POLISH LEGENDS',polishCopy:'Eight illustrated Polish legends, from the Wawel Dragon to the Sleeping Knights of the Tatras.',polishGraphic:'GRAPHIC EDITION'},
  uk:{library:'ЦИФРОВА БІБЛІОТЕКА',choose:'ОБЕРІТЬ ІСТОРІЮ',eyebrow:'ЧИТАЙТЕ · НАВЧАЙТЕСЯ · ПАМ’ЯТАЙТЕ',title:'БІБЛІОТЕКА',intro:'Оберіть українську історію та читайте її як графічний роман або як текст з інтерактивним словником.',fantasy:'ЕПІЧНЕ ФЕНТЕЗІ',series:'КАМЕНІ СПАРТИ',bookTitle:'ПЕРШЕ ПРОБУДЖЕННЯ',hellboy:'Міша обирає Спарту й починає пошуки Каменів Нескінченності.',folk:'НАРОДНІ КАЗКИ',folkTitle:'УКРАЇНСЬКІ НАРОДНІ КАЗКИ',folkBadge:'УКРАЇНСЬКА НАРОДНА КАЗКА',turnip:'РІПКА',turnipCopy:'Тепла казка про найменшого помічника, який робить те, чого не можуть інші.',mitten:'РУКАВИЧКА',mittenCopy:'Загублена вовняна рукавичка стає зимовою домівкою для сімох лісових друзів.',graphic:'ГРАФІЧНИЙ РОМАН',novel:'РОМАН'},
  pl:{library:'BIBLIOTEKA CYFROWA',choose:'WYBIERZ OPOWIEŚĆ',eyebrow:'CZYTAJ · POZNAWAJ · PAMIĘTAJ',title:'BIBLIOTEKA',intro:'Wybierz polską legendę i otwórz jej ilustrowane wydanie.',polishCategory:'POLSKIE LEGENDY',polishTitle:'POLSKIE BAŚNIE I LEGENDY',polishBadge:'POLSKIE BAŚNIE · TOM I',polishBook:'8 POLSKICH LEGEND',polishCopy:'Osiem ilustrowanych polskich legend — od Smoka Wawelskiego po Śpiących Rycerzy Tatr.',polishGraphic:'WYDANIE GRAFICZNE'}
};
const routeUk=/^\/ua(?:\/|$)/.test(location.pathname);const routePl=/^\/pl(?:\/|$)/.test(location.pathname);const lang=routeUk?'uk':routePl?'pl':'en';
const set=(id,v)=>{const el=document.getElementById(id);if(el&&v!=null)el.textContent=v};const c=copy[lang];document.documentElement.lang=lang;
set('libraryLabel',c.library);set('chooseLabel',c.choose);set('eyebrow',c.eyebrow);set('libraryTitle',c.title);set('libraryCopy',c.intro);
const fantasyShelf=document.getElementById('fantasyShelf'),ukrainianShelf=document.getElementById('ukrainianShelf'),polishShelf=document.getElementById('polishShelf');
if(lang==='en'){
  set('fantasyCategory',c.fantasy);document.querySelector('.hellboy-card .book-cover span').textContent=c.series;document.querySelector('.hellboy-card .book-cover h3').textContent=c.bookTitle;set('hellboyCopy',c.hellboy);set('folkCategory',c.folk);set('folkTitle',c.folkTitle);set('folkBadge',c.folkBadge);set('mittenBadge',c.folkBadge);document.getElementById('turnipTitle').innerHTML='THE<br>TURNIP';document.getElementById('mittenTitle').innerHTML='THE<br>MITTEN';set('turnipCopy',c.turnipCopy);set('mittenCopy',c.mittenCopy);for(const id of ['hellboyComic','turnipComic'])set(id,c.graphic);for(const id of ['hellboyNovel','turnipNovel','mittenNovel'])set(id,c.novel);set('polishCategory',c.polishCategory);set('polishTitle',c.polishTitle);set('polishBadge',c.polishBadge);document.getElementById('polishBookTitle').innerHTML='8 POLISH<br>LEGENDS';set('polishCopy',c.polishCopy);set('polishComic',c.polishGraphic);
}else if(lang==='uk'){
  fantasyShelf.hidden=true;polishShelf.hidden=true;set('folkCategory',c.folk);set('folkTitle',c.folkTitle);set('folkBadge',c.folkBadge);set('mittenBadge',c.folkBadge);document.getElementById('turnipTitle').textContent='РІПКА';document.getElementById('mittenTitle').textContent='РУКАВИЧКА';set('turnipCopy',c.turnipCopy);set('mittenCopy',c.mittenCopy);set('turnipComic',c.graphic);for(const id of ['turnipNovel','mittenNovel'])set(id,c.novel);document.getElementById('turnipComic').href='/ua/folk-tales/turnip/comic';document.getElementById('turnipNovel').href='/ua/folk-tales/turnip';document.getElementById('mittenNovel').href='/ua/folk-tales/mitten';
}else{
  fantasyShelf.hidden=true;ukrainianShelf.hidden=true;set('polishCategory',c.polishCategory);set('polishTitle',c.polishTitle);set('polishBadge',c.polishBadge);document.getElementById('polishBookTitle').innerHTML='8 POLSKICH<br>LEGEND';set('polishCopy',c.polishCopy);set('polishComic',c.polishGraphic);document.getElementById('polishComic').href='/pl/polish-folk-tales/collection/comic';
}
const select=document.getElementById('languageSelect');select.value=lang;select.onchange=()=>{localStorage.setItem('hellboy-language',select.value);location.href=select.value==='uk'?'/ua':select.value==='pl'?'/pl':'/'};

if(lang!=='pl'){
  const collectionCard=document.createElement('article');collectionCard.className='book-card collection-card';collectionCard.innerHTML=lang==='uk'?'<div class="book-cover"><span>ДВОМОВНА ЗБІРКА · ТОМ I</span><h3>13 НАРОДНИХ<br>КАЗОК</h3></div><div class="book-info"><p>Повна збірка з 13 казок: ілюстроване видання та розширена текстова версія українською мовою.</p><div class="book-actions"><a href="/ua/folk-tales/collection/comic">ГРАФІЧНЕ ВИДАННЯ</a><a href="/ua/folk-tales/collection">ТЕКСТОВЕ ВИДАННЯ</a></div></div>':'<div class="book-cover"><span>BILINGUAL COLLECTION · VOLUME I</span><h3>13 FOLK<br>TALES</h3></div><div class="book-info"><p>Thirteen complete tales in two formats: the illustrated collection and an expanded English text edition.</p><div class="book-actions"><a href="/folk-tales/collection/comic">GRAPHIC EDITION</a><a href="/folk-tales/collection">TEXT EDITION</a></div></div>';document.querySelector('.folk-grid').prepend(collectionCard);
  const coverEntries=[[document.querySelector('.hellboy-card .book-cover'),lang==='uk'?'/covers-lite/hellboy-uk.webp':'/covers-lite/hellboy.webp'],[document.querySelector('.turnip-card .book-cover'),lang==='uk'?'/covers-lite/turnip-uk.webp':'/covers-lite/turnip-en.webp'],[collectionCard.querySelector('.book-cover'),'/covers-lite/folk-collection.webp']].filter(([element])=>element);const loadCover=element=>{const entry=coverEntries.find(([candidate])=>candidate===element);if(!entry)return;element.style.setProperty('--library-cover',`url("${entry[1]}")`)};if('IntersectionObserver'in window){const coverObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;loadCover(entry.target);coverObserver.unobserve(entry.target)}},{rootMargin:'350px 0px',threshold:.01});coverEntries.forEach(([element])=>coverObserver.observe(element));}else coverEntries.forEach(([element])=>loadCover(element));
}
